# 1. PANDAS & NUMPY

In [1]:
import pandas as pd
import numpy as np

1-1 Numpy

In [24]:
list1 = [1, 2, 3, 4]
a = np.array(list1)

In [25]:
a

array([1, 2, 3, 4])

In [26]:
a.shape

(4,)

In [29]:
b = np.array([[1, 2, 3], [4, 5, 6]])   #array() 안에 하나의 리스트만 들어감!!!!!
b.shape

(2, 3)

In [30]:
def pprint(arr):
    print("type:{}".format(type(arr)))
    print("shape: {}, dimension: {}, dtype:{}".format(arr.shape, arr.ndim, arr.dtype))
    print("Array's Data:\n", arr)

In [ ]:
- np.zeros(shape, dtype = )
- np.ones(shape, dtype = )
- np.full(shape, fill_value, dtype = )
- np.eye(N, M, k, dtype = )
- np.empty()

### 1-1 Series
- pd.Series(list객체 or tuple객체 [, True, index=[리스트])
- pd.Series(딕셔너리)
- Series객체.index
- Series객체.values

In [2]:
obj = pd.Series([4, 7, -5, 3])
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [3]:
obj.values

array([ 4,  7, -5,  3], dtype=int64)

In [4]:
type(obj)

pandas.core.series.Series

In [5]:
# 인덱스를 바꿀 수 있다.
obj2 = pd.Series([4, 7, -5, 3], index=['d', 'b', 'a', 'c'])
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [6]:
# python의 dictionary 자료형을 Series data로 만들 수 있다.
# dictionary의 key가 Series의 index가 된다
sdata = {'Kim': 35000, 'Beomwoo': 67000, 'Joan': 12000, 'Choi': 4000}
obj3 = pd.Series(sdata)
obj3

Kim        35000
Beomwoo    67000
Joan       12000
Choi        4000
dtype: int64

In [11]:
obj3.name = 'Salary'

In [12]:
obj3.name

'Salary'

In [13]:
# index 변경
obj3.index = ['A', 'B', 'C', 'D']
obj3 

A    35000
B    67000
C    12000
D     4000
Name: Salary, dtype: int64

### 1-2 DataFrame
- pd.DataFrame(딕셔너리)
- pd.DataFrame(2차원배열, index = 행 인덱스 리스트, columns = 열 이름 리스트)
- df.index = 새로운 행 인덱스 리스트
- df.columns = 새로운 열 이름 리스트

In [14]:
#ndarray를 dataframe으로 생성
my_2darray = np.array([[1, 2, 3], [4, 5, 6]])
pd.DataFrame(my_2darray)

0  1  2
0  1  2  3
1  4  5  6

In [15]:
my_2darray

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
# dictionary를 DataFrame 으로 생성
my_dict = {"a": ['1', '3'], "b": ['1', '2'], "c": ['2', '4']}
pd.DataFrame(my_dict)

a  b  c
0  1  1  2
1  3  2  4

In [17]:
# 데이터, 인덱스, 컬럼으로 DataFrame 생성
my_df = pd.DataFrame(data=[4,5,6,7], index=range(0,4), columns=['A'])
pd.DataFrame(my_df)

A
0  4
1  5
2  6
3  7

In [23]:
# Series를 DataFrame으로 생성
my_series = pd.Series({"United Kingdom":"London", "India":"New Delhi", "United States":"Washington", "Belgium":"Brussels"})
pd.DataFrame(my_series, columns = ['Capital'])

Capital
United Kingdom      London
India            New Delhi
United States   Washington
Belgium           Brussels

- df.rename(index = {기존 인덱스: 새 인덱스, ...})
- df.rename(columns = {기존 인덱스: 새 인덱스, ...})

- df.drop(행 인덱스/인덱스 리스트, axis = 0, inplace = True)
- df.drop(열 이름/이름 리스트, axis = 1, inplace = True)

- df.set_index(['열이름'] 또는 '열 이름')
- df.reindex(새로운 인덱스 배열, fill_value = NaN 채울 값)
- df.reset_index()
- df.sort_index()

- df.sort_values(by = '열이름')


# TensorFlow

- Sequential() - 딥러닝의 구조를 한 층 한 층 쉽게 쌓아올릴 수 있게 해 줍니다. 
- Sequential 함수를 선언하고 나서 model.add() 함수를 사용해 필요한 층을 차례로 추가합니다.
- Dense( activation=, loss=, optimizer=) 각 층이 제각각 어떤 특성을 가질지 옵션을 설정하는 역할을 합니다.
    - activation: 다음 층으로 어떻게 값을 넘길지 결정하는 부분(가장 많이 사용되는 relu와 sigmoid 함수)
    - loss: 한 번 신경망이 실행될 때마다 오차 값을 추적하는 함수
    - optimizer: 오차를 어떻게 줄여 나갈지 정하는 함수
- model.evaluate() - 딥러닝의 모델이 어느 정도 정확하게 예측하는지를 점검


Keras
- 머신러닝 라이브러리 Theano와 TensorFlow를 래핑한 라이브러리
- Sequential로 딥러닝의 각 층을 add()로 추가
- 활성화 함수, Dropout 등 add()로 간단하게 추가
- compile()로 모델 구축
- loss 로 최적화 함수 지정
- fit() 로 모델에 데이터를 학습시킴
- Keras로 머신러닝을 수행할 때 Numpy 배열 데이터를 전달해야 한다

In [2]:
import tensorflow as tf
from keras.models import Sequential
from keras.layers.core import Dense, Dropout, Activation
from keras.callbacks import EarlyStopping
import pandas as pd, numpy as np

In [5]:
seed = 0
np.random.seed(seed)

In [7]:
tf.set_random_seed(seed)

In [12]:
# 실행할 때마다 같은 결과를 출력하기 위해 설정하는 부분입니다.
seed = 0
np.random.seed(seed)
tf.set_random_seed(seed)

# 준비된 수술 환자 데이터를 불러들입니다.
Data_set = np.loadtxt("./dataset/ThoraricSurgery.csv", delimiter=",")

# 환자의 기록과 수술 결과를 X와 Y로 구분하여 저장합니다.
X = Data_set[:,0:17]
Y = Data_set[:,17]

# 딥러닝 구조를 결정합니다(모델을 설정하고 실행하는 부분입니다).
model = Sequential()
model.add(Dense(30, input_dim=17, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

# 딥러닝을 실행합니다.
model.compile(loss='mean_squared_error', optimizer='adam', metrics=['accuracy'])
model.fit(X, Y, epochs=30, batch_size=10)

Instructions for updating:
If using Keras pass *_constraint arguments to layers.

Epoch 1/30
470/470 [==============================] - 0s 286us/step - loss: 0.6622 - accuracy: 0.3128
Epoch 2/30
470/470 [==============================] - 0s 57us/step - loss: 0.1488 - accuracy: 0.8511
Epoch 3/30
470/470 [==============================] - 0s 62us/step - loss: 0.1488 - accuracy: 0.8511
Epoch 4/30
470/470 [==============================] - 0s 67us/step - loss: 0.1488 - accuracy: 0.8511
Epoch 5/30
470/470 [==============================] - 0s 64us/step - loss: 0.1488 - accuracy: 0.8511
Epoch 6/30
470/470 [==============================] - 0s 65us/step - loss: 0.1487 - accuracy: 0.8511
Epoch 7/30
470/470 [==============================] - 0s 68us/step - loss: 0.1487 - accuracy: 0.8511
Epoch 8/30
470/470 [==============================] - 0s 64us/step - loss: 0.1487 - accuracy: 0.8511
Epoch 9/30
470/470 [==============================] - 0s 67us/step - loss: 0.1487 - accuracy: 0.8511
Epoch 10