# 1. 서울 중학교 졸업생 진로

In [4]:
import pandas as pd
import folium

In [22]:
df = pd.read_excel('./datas/2016_middle_shcool_graduates_report.xlsx', header = 0)

In [23]:
df

Unnamed: 0   지역               학교명  코드  유형  주야  남학생수  여학생수    일반고   특성화고  \
0             0  성북구    서울대학교사범대학부설중학교   3  국립  주간   277     0  0.585  0.148   
1             1  종로구  서울대학교사범대학부설여자중학교   3  국립  주간     0   256  0.680  0.199   
2             2  강남구             개원중학교   3  공립  주간   170   152  0.817  0.047   
3             3  강남구             개포중학교   3  공립  주간    83    72  0.755  0.097   
4             4  서초구             경원중학교   3  공립  주간   199   212  0.669  0.017   
..          ...  ...               ...  ..  ..  ..   ...   ...    ...    ...   
410         410  강남구           국립국악중학교   9  국립  주간     9    91  0.060  0.000   
411         411  금천구         국립전통예술중학교   9  국립  주간    14    42  0.107  0.000   
412         412  광진구            선화예술학교   9  사립  주간    33   241  0.102  0.000   
413         413   중구              예원학교   9  사립  주간    31   258  0.170  0.000   
414         414  노원구           한국삼육중학교   9  사립  주간   105   102  0.908  0.019   

     ...  외고_국제고  예고_체고  마이스터고    자사고    자공고   기타진학  취업     미상         위도  \
0    ...   0.007  0.000  0.011  0.227  0.000  0.004   0  0.000  37.594942   
1    ...   0.035  0.008  0.000  0.043  0.004  0.031   0  0.000  37.577473   
2    ...   0.012  0.003  0.006  0.090  0.003  0.009   0  0.003  37.491637   
3    ...   0.013  0.019  0.019  0.065  0.000  0.019   0  0.000  37.480439   
4    ...   0.010  0.005  0.000  0.282  0.000  0.010   0  0.000  37.510750   
..   ...     ...    ...    ...    ...    ...    ...  ..    ...        ...   
410  ...   0.000  0.940  0.000  0.000  0.000  0.000   0  0.000  37.476381   
411  ...   0.000  0.875  0.000  0.000  0.000  0.000   0  0.018  37.446354   
412  ...   0.000  0.861  0.000  0.000  0.000  0.000   0  0.036  37.549642   
413  ...   0.000  0.751  0.000  0.000  0.000  0.048   0  0.031  37.566951   
414  ...   0.024  0.000  0.010  0.010  0.000  0.029   0  0.000  37.641056   

             경도  
0    127.038909  
1    127.003857  
2    127.071744  
3    127.062201  
4    127.008900  
..          ...  
410  127.051355  
411  126.906424  
412  127.087737  
413  126.971553  
414  127.108344  

[415 rows x 21 columns]

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 415 entries, 0 to 414
Data columns (total 21 columns):
Unnamed: 0    415 non-null int64
지역            415 non-null object
학교명           415 non-null object
코드            415 non-null int64
유형            415 non-null object
주야            415 non-null object
남학생수          415 non-null int64
여학생수          415 non-null int64
일반고           415 non-null float64
특성화고          415 non-null float64
과학고           415 non-null float64
외고_국제고        415 non-null float64
예고_체고         415 non-null float64
마이스터고         415 non-null float64
자사고           415 non-null float64
자공고           415 non-null float64
기타진학          415 non-null float64
취업            415 non-null int64
미상            415 non-null float64
위도            415 non-null float64
경도            415 non-null float64
dtypes: float64(12), int64(5), object(4)
memory usage: 68.2+ KB


In [25]:
df.columns.values

array(['Unnamed: 0', '지역', '학교명', '코드', '유형', '주야', '남학생수', '여학생수', '일반고',
       '특성화고', '과학고', '외고_국제고', '예고_체고', '마이스터고', '자사고', '자공고', '기타진학',
       '취업', '미상', '위도', '경도'], dtype=object)

In [26]:
mschool_map = folium.Map(location = [37.55, 126.98], tiles = 'Stamen Terrain', zoom_start = 12)

for name, lat, lng in zip(df.학교명, df.위도, df.경도):
    folium.CircleMarker([lat, lng], radius = 5, color = 'brown', fill = True, fill_color = 'yellow', fill_opacity = 0.5, popup = name).add_to(mschool_map)

In [14]:
mschool_map

In [15]:
mschool_map.save('./output/seoul_mschool_location.html')

In [27]:
from sklearn import preprocessing

label_encoder = preprocessing.LabelEncoder()
onehot_encoder = preprocessing.OneHotEncoder()

onehot_location = label_encoder.fit_transform(df.지역)
onehot_code = label_encoder.fit_transform(df.코드)
onehot_type = label_encoder.fit_transform(df.유형)
onehot_day = label_encoder.fit_transform(df.주야)

In [28]:
df.지역 = onehot_location
df.코드 = onehot_code
df.유형 = onehot_type
df.주야 = onehot_day

In [29]:
df.head()

Unnamed: 0  지역               학교명  코드  유형  주야  남학생수  여학생수    일반고   특성화고  \
0           0  16    서울대학교사범대학부설중학교   0   1   0   277     0  0.585  0.148   
1           1  22  서울대학교사범대학부설여자중학교   0   1   0     0   256  0.680  0.199   
2           2   0             개원중학교   0   0   0   170   152  0.817  0.047   
3           3   0             개포중학교   0   0   0    83    72  0.755  0.097   
4           4  14             경원중학교   0   0   0   199   212  0.669  0.017   

   ...  외고_국제고  예고_체고  마이스터고    자사고    자공고   기타진학  취업     미상         위도  \
0  ...   0.007  0.000  0.011  0.227  0.000  0.004   0  0.000  37.594942   
1  ...   0.035  0.008  0.000  0.043  0.004  0.031   0  0.000  37.577473   
2  ...   0.012  0.003  0.006  0.090  0.003  0.009   0  0.003  37.491637   
3  ...   0.013  0.019  0.019  0.065  0.000  0.019   0  0.000  37.480439   
4  ...   0.010  0.005  0.000  0.282  0.000  0.010   0  0.000  37.510750   

           경도  
0  127.038909  
1  127.003857  
2  127.071744  
3  127.062201  
4  127.008900  

[5 rows x 21 columns]

In [30]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 415 entries, 0 to 414
Data columns (total 21 columns):
Unnamed: 0    415 non-null int64
지역            415 non-null int32
학교명           415 non-null object
코드            415 non-null int64
유형            415 non-null int32
주야            415 non-null int32
남학생수          415 non-null int64
여학생수          415 non-null int64
일반고           415 non-null float64
특성화고          415 non-null float64
과학고           415 non-null float64
외고_국제고        415 non-null float64
예고_체고         415 non-null float64
마이스터고         415 non-null float64
자사고           415 non-null float64
자공고           415 non-null float64
기타진학          415 non-null float64
취업            415 non-null int64
미상            415 non-null float64
위도            415 non-null float64
경도            415 non-null float64
dtypes: float64(12), int32(3), int64(5), object(1)
memory usage: 63.3+ KB


In [68]:
#DBSCAN 군집분석 수행
from sklearn import cluster
#분석에 사용할 속성 [과학고, 외고_국제고, 자사고 ] 진학률
column_list = [9, 10, 13]
X = df.iloc[ : , column_list]
print(X[:5])

    특성화고    과학고  마이스터고
0  0.148  0.018  0.011
1  0.199  0.000  0.000
2  0.047  0.009  0.006
3  0.097  0.013  0.019
4  0.017  0.007  0.000


In [69]:
X

특성화고    과학고  마이스터고
0    0.148  0.018  0.011
1    0.199  0.000  0.000
2    0.047  0.009  0.006
3    0.097  0.013  0.019
4    0.017  0.007  0.000
..     ...    ...    ...
410  0.000  0.000  0.000
411  0.000  0.000  0.000
412  0.000  0.000  0.000
413  0.000  0.000  0.000
414  0.019  0.000  0.010

[415 rows x 3 columns]

In [70]:
#설명변수 정규화
X = preprocessing.StandardScaler().fit(X).transform(X)

#클러스터링
dbscan_model = cluster.DBSCAN(eps = 0.2, min_samples = 5)
dbscan_model.fit(X)

cluster_label = dbscan_model.labels_

In [71]:
cluster_label     #-1은 노이즈

array([-1,  0, -1, -1,  1,  5, -1, -1,  2, -1, -1, -1,  2,  0, -1, -1, -1,
       -1, -1,  2, -1, -1, -1,  0,  1,  2, -1,  1,  0,  0, -1, -1, -1, -1,
       -1,  0, -1, -1, -1, -1, -1, -1, -1,  0, -1, -1, -1,  3, -1, -1, -1,
        3, -1,  1, -1, -1,  4, -1, -1,  4, -1, -1,  4,  0, -1,  5,  0,  6,
        1, -1,  0,  1, -1,  0,  8, -1, -1, -1,  4, -1,  3, -1, -1,  3,  4,
       -1, -1, -1,  3, -1,  0,  2, -1,  0, -1, -1,  5,  0,  0, -1, -1, -1,
       -1, -1, -1, -1, -1,  0, -1, -1, -1, -1, -1, -1,  1, -1, -1, -1,  0,
       -1, -1, -1,  5,  8,  0, -1, -1, -1, -1, -1,  7,  3,  0, -1,  5,  0,
        4, -1,  5, -1, -1, -1, -1, -1, -1,  6, -1, -1, -1,  8,  4, -1, -1,
        6, -1, -1, -1, -1, -1,  0,  6, -1, -1, -1, -1, -1, -1,  6, -1, -1,
        7, -1, -1,  6, -1,  0,  0, -1,  3, -1,  6,  8, -1,  6, -1, -1, -1,
       -1, -1, -1,  5,  0,  0, -1, -1, -1, -1,  0,  0, -1,  0, -1, -1,  6,
        0, -1, -1, -1, -1, -1,  4, -1, -1,  3, -1, -1,  0, -1, -1,  9, -1,
       -1, -1, -1, -1, -1

In [72]:
df['Cluster'] = cluster_label

In [73]:
df.head()

Unnamed: 0  지역               학교명  코드  유형  주야  남학생수  여학생수    일반고   특성화고  \
0           0  16    서울대학교사범대학부설중학교   0   1   0   277     0  0.585  0.148   
1           1  22  서울대학교사범대학부설여자중학교   0   1   0     0   256  0.680  0.199   
2           2   0             개원중학교   0   0   0   170   152  0.817  0.047   
3           3   0             개포중학교   0   0   0    83    72  0.755  0.097   
4           4  14             경원중학교   0   0   0   199   212  0.669  0.017   

   ...  예고_체고  마이스터고    자사고    자공고   기타진학  취업     미상         위도          경도  \
0  ...  0.000  0.011  0.227  0.000  0.004   0  0.000  37.594942  127.038909   
1  ...  0.008  0.000  0.043  0.004  0.031   0  0.000  37.577473  127.003857   
2  ...  0.003  0.006  0.090  0.003  0.009   0  0.003  37.491637  127.071744   
3  ...  0.019  0.019  0.065  0.000  0.019   0  0.000  37.480439  127.062201   
4  ...  0.005  0.000  0.282  0.000  0.010   0  0.000  37.510750  127.008900   

   Cluster  
0       -1  
1        0  
2       -1  
3       -1  
4        1  

[5 rows x 22 columns]

In [74]:
grouped_cols = [0, 1, 3] + column_list
grouped = df.groupby('Cluster')

In [75]:
grouped_cols

[0, 1, 3, 9, 10, 13]

In [76]:
for key, group in grouped:
    print('* key: ', key)
    print('* number: ', len(group))
    print(group.iloc[:, grouped_cols].head())
    print('\n')

* key:  -1
* number:  234
   Unnamed: 0  지역  코드   특성화고    과학고  마이스터고
0           0  16   0  0.148  0.018  0.011
2           2   0   0  0.047  0.009  0.006
3           3   0   0  0.097  0.013  0.019
6           6   0   0  0.015  0.015  0.000
7           7   0   0  0.000  0.032  0.000


* key:  0
* number:  70
    Unnamed: 0  지역  코드   특성화고  과학고  마이스터고
1            1  22   0  0.199  0.0    0.0
13          13  14   0  0.032  0.0    0.0
23          23   0   0  0.025  0.0    0.0
28          28  14   0  0.040  0.0    0.0
29          29   0   0  0.051  0.0    0.0


* key:  1
* number:  7
    Unnamed: 0  지역  코드   특성화고    과학고  마이스터고
4            4  14   0  0.017  0.007    0.0
24          24   0   0  0.026  0.007    0.0
27          27   0   0  0.006  0.006    0.0
53          53   1   0  0.020  0.007    0.0
68          68  17   0  0.011  0.007    0.0


* key:  2
* number:  6
    Unnamed: 0  지역  코드   특성화고    과학고  마이스터고
8            8   0   0  0.018  0.013    0.0
12          12   0   0  0.000  0.013

#### 클러스터 결과 적용해서 다시 맵핑

In [77]:
colors = {-1: 'gray', 0: 'coral', 1: 'black', 2:'green', 3:'red', 4:'purple', 5:'orange', 6:'brown', 7: 'magenta', 8: 'yellow', 9: 'brick', 10: 'cyan', 11: 'pink'}

In [78]:
mschool_map_classed = folium.Map(location = [37.55, 126.98], tiles = 'Stamen Terrain', zoom_start = 12)

for name, lat, lng, clus in zip(df.학교명, df.위도, df.경도, df.Cluster):
    folium.CircleMarker([lat, lng], radius = 5, color = colors[clus], fill = True, fill_color = colors[clus], fill_opacity = 0.5, popup = name).add_to(mschool_map_classed)

In [79]:
mschool_map_classed

In [47]:
mschool_map_classed.save('./output/mschool_map_classed.html')

# 2. LabelEncoder 예제

In [88]:
import numpy as np
from sklearn.preprocessing import LabelEncoder

X_train = np.array(['MOBILE', 'NOTEBOOK', 'DESKTOP'])
X_test = np.array(['MOBILE', 'NOTEBOOK', 'TABLET'])

In [92]:
encoder = LabelEncoder()
encoder.fit(X_train)
x_train_encoded = encoder.transform(X_train)

print(x_train_encoded)
print(encoder.classes_)
print('\n')

for label in np.unique(X_test):
    if label not in encoder.classes_:
        encoder.classes_ = np.append(encoder.classes_, label)
        
x_test_encoded = encoder.transform(X_test)

print(x_test_encoded)
print(encoder.classes_)
print('\n')


[1 2 0]
['DESKTOP' 'MOBILE' 'NOTEBOOK']


[1 2 3]
['DESKTOP' 'MOBILE' 'NOTEBOOK' 'TABLET']




In [94]:
result = encoder.inverse_transform([2, 1, 0, 3])
print(result)

['NOTEBOOK' 'MOBILE' 'DESKTOP' 'TABLET']
