# NUMPY

In [1]:
import numpy as np

In [219]:
my_arr = np.arange(1000000)

In [220]:
my_list = list(range(1000000))

In [229]:
%time for _ in range(10): my_arr2 = my_arr*2

Wall time: 19.9 ms


In [230]:
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

Wall time: 591 ms


In [231]:
data = np.random.randn(2, 3)

In [232]:
data

array([[-0.75474483,  0.3354411 ,  0.64925437],
       [ 0.73619977,  0.62078415,  1.12864706]])

배열 객체 생성: array(), arange(), zeros(), ones(), full(), eye(), logspace(), linspace(), empty()

난수로 초기화해서 생성: np.random.normal(), rand(), randint(), random()

In [6]:
def pprint(arr):
    print("type:{}".format(type(arr)))
    print("shape: {}, dimension: {}, dtype:{}".format(arr.shape, arr.ndim, arr.dtype))
    print("Array's Data:\n", arr)

In [3]:
a = np.arange(27).reshape(3, 3, 3)
print(a)
a.sum(axis = 0)  #면(각 면에서 동일한 위치의 요소의 누적합)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


array([[27, 30, 33],
       [36, 39, 42],
       [45, 48, 51]])

In [244]:
a = np.arange(28)

In [245]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27])

In [4]:
a.sum(axis = 1) #행

array([[ 9, 12, 15],
       [36, 39, 42],
       [63, 66, 69]])

In [5]:
a.sum(axis = 2)  #열

array([[ 3, 12, 21],
       [30, 39, 48],
       [57, 66, 75]])

### ufunc

In [7]:
arr = np.arange(10)

In [8]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [10]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [11]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.modf(arr)

(array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
 array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [13]:
a = np.arange(1, 10).reshape(3, 3)
pprint(a)
b = np.arange(9, 0, -1).reshape(3, 3)
pprint(b)

type:<class 'numpy.ndarray'>
shape: (3, 3), dimension: 2, dtype:int32
Array's Data:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
type:<class 'numpy.ndarray'>
shape: (3, 3), dimension: 2, dtype:int32
Array's Data:
 [[9 8 7]
 [6 5 4]
 [3 2 1]]


In [15]:
a - b

array([[-8, -6, -4],
       [-2,  0,  2],
       [ 4,  6,  8]])

In [16]:
np.subtract(a, b)

array([[-8, -6, -4],
       [-2,  0,  2],
       [ 4,  6,  8]])

In [18]:
print(a+b)
print(np.add(a, b))

print('\n')

print(a/b)
print(np.divide(a, b))

print('\n')

print(a*b)
print(np.multiply(a, b))

[[10 10 10]
 [10 10 10]
 [10 10 10]]
[[10 10 10]
 [10 10 10]
 [10 10 10]]


[[0.11111111 0.25       0.42857143]
 [0.66666667 1.         1.5       ]
 [2.33333333 4.         9.        ]]
[[0.11111111 0.25       0.42857143]
 [0.66666667 1.         1.5       ]
 [2.33333333 4.         9.        ]]


[[ 9 16 21]
 [24 25 24]
 [21 16  9]]
[[ 9 16 21]
 [24 25 24]
 [21 16  9]]


In [19]:
a = np.arange(1, 10).reshape(3, 3)

In [20]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
a.sum()

45

In [22]:
np.sum(a)

45

In [23]:
a.sum(axis = 0)

array([12, 15, 18])

In [24]:
np.sum(a, axis = 0)

array([12, 15, 18])

In [25]:
a.sum(axis = 1)

array([ 6, 15, 24])

In [26]:
np.sum(a, axis = 1)

array([ 6, 15, 24])

In [29]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [33]:
np.cumsum(a)

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45], dtype=int32)

In [31]:
np.median(a)

5.0

In [34]:
np.mean(a)

5.0

In [35]:
np.corrcoef(a)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [36]:
np.std(a)

2.581988897471611

In [37]:
a.std()

2.581988897471611

# 입출력

In [38]:
import random

In [56]:
a = np.random.randint(0, 10, (2, 3))

In [41]:
a

array([[9, 3, 6],
       [4, 2, 2]])

In [58]:
b = np.random.randint(0, 10, (2, 3))

In [43]:
b

array([[1, 5, 7],
       [0, 8, 6]])

In [45]:
pprint(a)
pprint(b)

type:<class 'numpy.ndarray'>
shape: (2, 3), dimension: 2, dtype:int32
Array's Data:
 [[9 3 6]
 [4 2 2]]
type:<class 'numpy.ndarray'>
shape: (2, 3), dimension: 2, dtype:int32
Array's Data:
 [[1 5 7]
 [0 8 6]]


In [47]:
#a 배열 파일에 저장
np.save("./my_array1", a)

In [62]:
#a, b 배열 파일에 저장
np.savez("./my_array2", a, b)

In [49]:
#디렉토리에 있는 파일 리스트 보기
! dir/w

 C 드라이브의 볼륨에는 이름이 없습니다.
 볼륨 일련 번호: 78D5-6279

 C:\Users\student\ipynb 디렉터리

[.]                          [..]
[.ipynb_checkpoints]         12.11)연습문제.ipynb
1211)연습문제_테스트.ipynb   1212)연습문제.ipynb
count_log.txt                dec10.ipynb
dec11.ipynb                  dec12.ipynb
dec13.ipynb                  dec16_NUMPY.ipynb
dream.txt                    [log]
my_array1.npy                my_array2.npy
[roboadvisor]                test3.py
[__pycache__]                
              13개 파일             137,482 바이트
               6개 디렉터리  202,859,331,584 바이트 남음


In [50]:
del a
del b
pprint(a)

NameError: name 'a' is not defined

In [54]:
c = np.load("./my_array1.npy")

In [53]:
c

array([[9, 3, 6],
       [4, 2, 2]])

In [63]:
npzfiles = np.load("./my_array2.npz")
npzfiles.files

['arr_0', 'arr_1']

In [67]:
npzfiles["arr_0"]

array([[9, 1, 5],
       [7, 2, 9]])

In [72]:
data1 = np.loadtxt("./data/simple.csv")
pprint(data1)

type:<class 'numpy.ndarray'>
shape: (2, 3), dimension: 2, dtype:float64
Array's Data:
 [[1. 2. 3.]
 [4. 5. 6.]]


In [73]:
data1 = np.loadtxt("./data/simple.csv", dtype = np.int)
pprint(data1)

type:<class 'numpy.ndarray'>
shape: (2, 3), dimension: 2, dtype:int32
Array's Data:
 [[1 2 3]
 [4 5 6]]


In [76]:
data2 = np.loadtxt("./data/president.csv", delimiter = ",", skiprows = 1, dtype = {'names': ("order", "name", "height"), 'formats':('i', 'S20', 'f')})

In [78]:
data2[:3]

array([(1, b" 'George Washington'", 178.5), (2, b" 'John Adams'", 169. ),
       (3, b" 'Thomas Jefferson'", 158. )],
      dtype=[('order', '<i4'), ('name', 'S20'), ('height', '<f4')])

In [79]:
#도움말 보기
np.info(np.ndarray.dtype)

Data-type of the array's elements.

Parameters
----------
None

Returns
-------
d : numpy dtype object

See Also
--------
numpy.dtype

Examples
--------
>>> x
array([[0, 1],
       [2, 3]])
>>> x.dtype
dtype('int32')
>>> type(x.dtype)
<type 'numpy.dtype'>


# 배열 형태 변경

ravel, reshape, resize, append, insert, delete, concatenate, vstack, hstack, hsplit, vplit

In [80]:
a = np.random.randint(1, 10, (2, 3))

In [82]:
a

array([[8, 1, 5],
       [8, 8, 3]])

In [81]:
a.ravel()

array([8, 1, 5, 8, 8, 3])

In [83]:
b = a.ravel()  #1차원 배열로 변경해주는 함수 / 원본배열도 수정

In [84]:
pprint(b)

type:<class 'numpy.ndarray'>
shape: (6,), dimension: 1, dtype:int32
Array's Data:
 [8 1 5 8 8 3]


In [86]:
b[0] = 99

In [89]:
b

array([99,  1,  5,  8,  8,  3])

In [90]:
a

array([[99,  1,  5],
       [ 8,  8,  3]])

In [91]:
result = a.reshape((3, 2, 1))  #3면의 2행의 1열로 바꿔라 / 원본배열은 수정하지 않음

In [92]:
result

array([[[99],
        [ 1]],

       [[ 5],
        [ 8]],

       [[ 8],
        [ 3]]])

In [101]:
a = np.random.randint(1, 10, (2, 6))

In [102]:
np.resize(a, (6, 2))  #배열 모양을 바꾸는 건 reshape과 동일하지만, 요소의 수 변동

array([[4, 9],
       [5, 5],
       [3, 6],
       [2, 9],
       [3, 8],
       [6, 3]])

In [105]:
np.resize(a, (10, 10))

array([[4, 9, 5, 5, 3, 6, 2, 9, 3, 8],
       [6, 3, 4, 9, 5, 5, 3, 6, 2, 9],
       [3, 8, 6, 3, 4, 9, 5, 5, 3, 6],
       [2, 9, 3, 8, 6, 3, 4, 9, 5, 5],
       [3, 6, 2, 9, 3, 8, 6, 3, 4, 9],
       [5, 5, 3, 6, 2, 9, 3, 8, 6, 3],
       [4, 9, 5, 5, 3, 6, 2, 9, 3, 8],
       [6, 3, 4, 9, 5, 5, 3, 6, 2, 9],
       [3, 8, 6, 3, 4, 9, 5, 5, 3, 6],
       [2, 9, 3, 8, 6, 3, 4, 9, 5, 5]])

In [106]:
a.resize((10, 10))

In [109]:
np.resize(a, (3, 3))

array([[4, 9, 5],
       [5, 3, 6],
       [2, 9, 3]])

In [110]:
a = np.arange(1, 10).reshape(3, 3)

In [112]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [233]:
b = np.arange(10, 19).reshape(3, 3)

In [234]:
b

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [235]:
b.shape

(3, 3)

In [114]:
result = np.append(a, b) #축 지정하지 않으면 1차원으로 각각 변환되어 첫번째 요소 뒤에 두번째 요소 append

In [115]:
result

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18])

In [116]:
result2 = np.append(a, b, axis = 0)

In [117]:
result2

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [118]:
result3 = np.append(a, b, axis = 1)

In [119]:
result3

array([[ 1,  2,  3, 10, 11, 12],
       [ 4,  5,  6, 13, 14, 15],
       [ 7,  8,  9, 16, 17, 18]])

In [120]:
different_sahpe_arr = np.arange(10, 20).reshape(2, 5)

In [121]:
different_sahpe_arr

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [122]:
np.append(a, different_sahpe_arr, axis = 0) # 모양이 다를 시 append 불가

ValueError: all the input array dimensions except for the concatenation axis must match exactly

In [124]:
different_sahpe_arr1 = np.arange(10, 22).reshape(4, 3)

In [126]:
different_sahpe_arr1

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21]])

In [125]:
np.append(a, different_sahpe_arr1, axis = 0) #붙는 부분만 행/열 수 같으면 됨

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21]])

In [127]:
np.append(a, different_sahpe_arr1, axis = 1)

ValueError: all the input array dimensions except for the concatenation axis must match exactly

In [128]:
a = np.arange(1, 10).reshape(3, 3)
pprint(a)

type:<class 'numpy.ndarray'>
shape: (3, 3), dimension: 2, dtype:int32
Array's Data:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [129]:
np.insert(a, 1, 999)

array([  1, 999,   2,   3,   4,   5,   6,   7,   8,   9])

In [131]:
np.insert(a, 1, 999, axis = 0)

array([[  1,   2,   3],
       [999, 999, 999],
       [  4,   5,   6],
       [  7,   8,   9]])

In [133]:
np.insert(a, 1, 999, axis = 1)

array([[  1, 999,   2,   3],
       [  4, 999,   5,   6],
       [  7, 999,   8,   9]])

In [135]:
np.delete(a, 1)

array([1, 3, 4, 5, 6, 7, 8, 9])

In [137]:
np.delete(a, 1, axis = 0)

array([[1, 2, 3],
       [7, 8, 9]])

In [138]:
np.delete(a, 1, axis = 1)

array([[1, 3],
       [4, 6],
       [7, 9]])

In [143]:
a = np.arange(1, 7).reshape(2, 3)
b = np.arange(7, 13).reshape(2, 3)

result = np.concatenate((a, b))

In [145]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [146]:
b

array([[ 7,  8,  9],
       [10, 11, 12]])

In [144]:
result

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [149]:
result1 = np.concatenate((a, b), axis = 1)

In [150]:
result1

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [151]:
result3 = np.vstack((a, b))  #수직방향 결합
result4 = np.hstack((a, b))

In [152]:
result3

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [153]:
result4

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [156]:
a = np.arange(1, 9).reshape(2, 4)

In [159]:
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [157]:
result5 = np.hsplit(a, 2)

In [158]:
result5

[array([[1, 2],
        [5, 6]]), array([[3, 4],
        [7, 8]])]

In [163]:
x, y = np.vsplit(b, 2)

# PANDAS

In [1]:
import pandas as pd

### series

In [2]:
dict_data = {'a':1, 'b':2, 'c':3}
sr = pd.Series(dict_data)

In [3]:
sr

a    1
b    2
c    3
dtype: int64

In [167]:
type(sr)

pandas.core.series.Series

In [168]:
type(dict_data)

dict

In [4]:
list_data = ['2019-12-16', 3.14, 'ABC', 100, True]
sr1 = pd.Series(list_data)

In [5]:
type(sr1)

pandas.core.series.Series

In [6]:
sr1

0    2019-12-16
1          3.14
2           ABC
3           100
4          True
dtype: object

In [178]:
sr1.index

RangeIndex(start=0, stop=5, step=1)

In [7]:
sr1.index = ['1', '2', '3', '4', '5']

In [8]:
sr1

1    2019-12-16
2          3.14
3           ABC
4           100
5          True
dtype: object

In [179]:
sr1.values

array(['2019-12-16', 3.14, 'ABC', 100, True], dtype=object)

In [181]:
tup_data = ('2019-12-16', 3.14, 'ABC', 100, True)
sr2 = pd.Series(tup_data, index = ['today', '원주율', '초코렛', '점수', '승인'])

In [182]:
type(sr2)

pandas.core.series.Series

In [183]:
sr2

today    2019-12-16
원주율            3.14
초코렛             ABC
점수              100
승인             True
dtype: object

In [187]:
sr2[0]

'2019-12-16'

In [185]:
sr2['today']

'2019-12-16'

In [188]:
sr2[[0, 2]]

today    2019-12-16
초코렛             ABC
dtype: object

In [190]:
sr2[0:3]

today    2019-12-16
원주율            3.14
초코렛             ABC
dtype: object

In [191]:
pd.isnull(sr2)

today    False
원주율      False
초코렛      False
점수       False
승인       False
dtype: bool

In [193]:
pd.notnull(sr2)

today    True
원주율      True
초코렛      True
점수       True
승인       True
dtype: bool

In [207]:
dict_data2 = {'b':2, 'a':1, 'd':np.nan, 'c':3}

In [216]:
dict_data3 = {'a':1, 'b':2, 'c':3, 'd':4}

In [208]:
sr3 = pd.Series(dict_data2)

In [217]:
sr4 = pd.Series(dict_data3)

In [209]:
sr3

b    2.0
a    1.0
d    NaN
c    3.0
dtype: float64

In [210]:
pd.isnull(sr3)

b    False
a    False
d     True
c    False
dtype: bool

In [211]:
sr3.isnull()

b    False
a    False
d     True
c    False
dtype: bool

In [218]:
sr3 + sr4

a    2.0
b    4.0
c    6.0
d    NaN
dtype: float64