In [1]:
import numpy as np

In [2]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [3]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
a.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
a.reshape((9, -1))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

# broadcasting